# Use the official Nginx image as the base image
FROM nginx:1.27.2

# Copy the HTML file to the Nginx HTML directory
COPY wordsList.html /usr/share/nginx/html/

# Expose port 80 to allow external access
EXPOSE 80
